project:
  type: book
  title: "クラウドエッジ技術調査報告書"
  output-dir: _book

book:
  title: "クラウドエッジ技術に関する調査報告書"
  subtitle: "日本の産業界における戦略的機会の分析"
  author: "dobachi"
  date: "2025-09-27"

  chapters:
    - index.qmd
    - cloud_edge_technology_research.qmd

  downloads: [pdf, epub]

  sidebar:
    search: true
    collapse-level: 3

  navbar:
    title: "クラウドエッジ技術調査報告書"
    background: primary
    search: true

  page-footer:
    left: "© 2025 dobachi"
    right: "Built with Quarto"

format:
  html:
    theme: cosmo
    css: templates/styles/report-style.css
    toc: true
    toc-depth: 4
    toc-location: left
    number-sections: true
    number-depth: 4
    code-fold: true
    code-tools: true
    smooth-scroll: true
    anchor-sections: true
    citations-hover: true
    crossrefs-hover: true
    fig-responsive: true
    embed-resources: false
    page-layout: full
    max-width: 1200px
    margin-left: auto
    margin-right: auto

  pdf:
    documentclass: book
    toc: true
    toc-depth: 4
    number-sections: true
    number-depth: 4
    colorlinks: true
    geometry:
      - top=2cm
      - bottom=2cm
      - left=2cm
      - right=2cm
    fontsize: 10pt
    mainfont: "Noto Serif CJK JP"
    sansfont: "Noto Sans CJK JP"
    monofont: "Noto Sans Mono CJK JP"
    include-in-header:
      - text: |
          \usepackage{fancyhdr}
          \pagestyle{fancy}
          \fancyhf{}
          \fancyhead[L]{クラウドエッジ技術調査報告書}
          \fancyhead[R]{\thepage}
          \fancyfoot[C]{dobachi}

  epub:
    toc: true
    toc-depth: 4
    number-sections: true
    number-depth: 4

bibliography: references.bib
csl: https://www.zotero.org/styles/apa
locale: locales-ja-JP.xml
link-citations: true

crossref:
  fig-title: "図"
  tbl-title: "表"
  eq-title: "式"
  sec-prefix: "第"
  fig-prefix: "図"
  tbl-prefix: "表"
  eq-prefix: "式"
  chapters: true

lang: ja

execute:
  freeze: auto

# filters:
#   - pandoc-crossref  # Quartoの組み込み機能を使用