# クラウドエッジ技術調査報告書設定ファイル

# 報告書の基本情報
report:
  title: "クラウドエッジ技術に関する調査報告書"
  subtitle: "日本の産業界における戦略的機会の分析"
  version: "1.0"
  date: "2025-09-27"
  language: "ja"  # ja: 日本語, en: 英語

# 調査テーマと範囲
research:
  topic: "クラウドエッジ技術の体系的分析と産業戦略"
  scope:
    - "IoTエッジコンピューティング"
    - "5G/6G通信技術"
    - "エッジAI技術"
    - "産業用IoT"
    - "車載システム"
    - "製造業DX"
    - "スマートシティ技術"

  period:
    start: "2024-12-01"
    end: "2025-09-27"

  objectives:
    - "クラウドエッジ技術の体系的分類と特徴の整理"
    - "グローバル市場動向と成長領域の特定"
    - "日本企業の技術的強みと弱みの分析"
    - "新産業領域確立のための具体的施策の提言"

# 作成者情報
authors:
  primary:
    name: "ResearchEdgeCloudTech調査チーム"
    organization: "クラウドエッジ技術研究プロジェクト"
    email: "research@edge-cloud-tech.project"

  contributors:
    - name: "AI指示書システム"
      role: "調査・分析支援"
    - name: "技術専門家"
      role: "技術検証・レビュー"

# 出力設定
output:
  formats:
    - markdown  # 基本形式
    - html      # Webブラウザ表示用
    - pdf       # 印刷・配布用

  html:
    template: "templates/report-template.html"
    css: "templates/styles/report-style.css"
    toc: true  # 目次の自動生成
    toc_depth: 3  # 目次の深さ

  pdf:
    paper_size: "A4"
    margin: "2cm"
    font_size: "10pt"
    header: true
    footer: true
    page_numbers: true

# 品質管理設定
quality:
  # 引用管理
  citation:
    style: "apa"  # APA, MLA, Chicago, IEEE など
    min_sources: 10  # 最小参考文献数
    require_doi: false  # DOIの必須化

  # 信頼性基準
  reliability:
    prefer_sources:
      - "government"     # 政府・行政機関（経産省、総務省）
      - "academic"       # 学術論文（IEEE、ACM）
      - "standards"      # 標準化団体（3GPP、ETSI、ITU-T）
      - "official"       # 企業公式文書・技術白書
      - "research"       # 調査機関（IDC、Gartner、McKinsey）

    avoid_sources:
      - "wikipedia"      # 一次情報源として避ける
      - "blog"          # 個人ブログ
      - "social_media"  # SNS投稿

  # レビュープロセス
  review:
    required: true
    min_reviewers: 2
    checklist:
      - "事実の正確性"
      - "引用の適切性"
      - "論理的一貫性"
      - "読みやすさ"

# テンプレート設定
templates:
  report: "templates/report_template.md"
  executive_summary: "templates/executive_summary.md"
  bibliography: "templates/bibliography.md"

# 調査分野別の設定
domains:
  cloud_edge_technology:
    sources:
      - "IEEE Xplore"
      - "3GPP Specifications"
      - "ETSI Standards"
      - "ITU-T Recommendations"
      - "IDC Research"
      - "Gartner Reports"
      - "McKinsey Institute"
      - "CNCF (Cloud Native Computing Foundation)"
    keywords:
      - "エッジコンピューティング"
      - "5G/6G"
      - "IoT"
      - "Multi-access Edge Computing (MEC)"
      - "Network Function Virtualization"
      - "コンテナオーケストレーション"
      - "エッジAI"

  industrial_iot:
    sources:
      - "Industrial Internet Consortium"
      - "OPC Foundation"
      - "経済産業省製造産業局"
      - "Enterprise IoT Platforms"
    keywords:
      - "OT/IT統合"
      - "デジタルツイン"
      - "予知保全"
      - "スマートファクトリー"
      - "産業4.0"

  mobile_communications:
    sources:
      - "3GPP"
      - "ITU-T"
      - "総務省"
      - "NTTドコモ技術文書"
      - "KDDI Research"
    keywords:
      - "5G SA"
      - "Network Slicing"
      - "URLLC"
      - "mMTC"
      - "ローカル5G"

# 自動化設定
automation:
  # 参考文献の自動フォーマット
  auto_format_references: true

  # 引用のチェック
  check_citations: true

  # 目次の自動生成
  auto_generate_toc: true

  # 用語集の自動生成
  auto_generate_glossary: false

# プラグイン設定（将来の拡張用）
plugins:
  - name: "citation-checker"
    enabled: true
  - name: "fact-verifier"
    enabled: false
  - name: "translation"
    enabled: false